### ISSUE TITLE
Cool stuff

### ISSUE THREAD

**Issue by junpenglao** [tomwallis/lab_helpers#1]
This is not really an issue just want to say this is awesome! Our lab also using Viewpixx3D and PTB and planning to move to Psychopy for some time now. Our undergrad already using psychopy via GUI to build behavioural experiments, but we have quite a lot of legacy code in PTB communicating with eye tracker (eyelink) and EEG (biosemi) so the moving have been slow.

**Comment by tomwallis** [comment]
Hey neat! We also use eyelink. I haven't looked into that much yet, but I'm aware that there are a couple of existing libraries for eyetracking (pylink?) that will hopefully make that easy. No idea about EEG.

If you're interested in helping out, I'm using this repository for hacky scripts to test stuff, but I'm planning to do the actual psychopy side into my fork of the psychopy repo [here](https://github.com/tomwallis/psychopy). There's a thread on the discussion forum about VPIXX-related stuff [here](https://discourse.psychopy.org/t/vpixx-hardware-class/3621). 

Once I have some working VPIXX code, I'd of course be very happy if you'd like to test it out on your system.

**Comment by tomwallis** [comment]
Hey @junpenglao: I just got some more time to work on this and am of course hitting many snags. Did you guys make any progress on this?

**Comment by junpenglao** [comment]
I haven't have time to look into it yet unfortunately :-/ Hopefully a bit more time to actually get started at the end of April.
